version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && 
             rm -f tmp/pids/unicorn.pid && 
             dockerize -wait tcp://db:3306 -timeout 20s bundle exec unicorn -p 3000 -c /muscle-master/config/unicorn.conf.rb"
    tty: true 
    stdin_open: true
    depends_on:
      - db 
    ports:
      - "3000:3000"
    volumes:
      - .:/muscle-master:cached 
      - tmp-data:/muscle-master/tmp/sockets
      - public-data:/muscle-master/public
  
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports: 
      - "4306:3306"
    environment:
      MYSQL_DATABASE: muscle_master_development
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: always 
    volumes:
      - tmp-data:/muscle-master/tmp/sockets
      - public-data:/muscle-master/public
    depends_on:
      - web 
  
volumes:
  public-data:
  tmp-data:
  mysql-data:
